[project]
name = "house-price-prediction"
version = "1.0.0"
description = "House Price Prediction API"
requires-python = "==3.12.*"

dependencies = [
    "fastapi[standard]",
    "uvicorn",
    "pandas==3.0.5",
    "scikit-learn==1.9.0",
    "joblib==1.5.3",
    "numpy==2.5.1"
]

[tool.fastapi]
entrypoint = "main:app"